export const SEND_FR_REQUEST = "SEND_FR_REQUEST";
export const SEND_FR_SUCCESS = "SEND_FR_SUCCESS";
export const SEND_FR_FAIL = "SEND_FR_FAIL";

export const ACCEPT_FR_REQUEST = "ACCEPT_FR_REQUEST";
export const ACCEPT_FR_SUCCESS = "ACCEPT_FR_SUCCESS";
export const ACCEPT_FR_FAIL = "ACCEPT_FR_FAIL";

export const SET_CHAT_INFO = "SET_CHAT_INFO";
export const GET_CHAT_HISTORY = "GET_CHAT_HISTORY";
