export const SEND_FR_REQUEST = 'SEND_FR_REQUEST';
export const SEND_FR_SUCCESS = 'SEND_FR_SUCCESS';
export const SEND_FR_FAIL = 'SEND_FR_FAIL';

export const ACCEPT_FR_REQUEST = 'ACCEPT_FR_REQUEST';
export const ACCEPT_FR_SUCCESS = 'ACCEPT_FR_SUCCESS';
export const ACCEPT_FR_FAIL = 'ACCEPT_FR_FAIL';

export const SET_CHAT_INFO_FAILURE = 'SET_CHAT_INFO_FAILUER';
export const SET_CHAT_INFO_REQUEST = 'SET_CHAT_INFO_REQUEST';
export const SET_CHAT_INFO_SUCCESS = 'SET_CHAT_INFO_SUCCESS';
export const GET_CHAT_HISTORY = 'GET_CHAT_HISTORY';

export const UPDATE_CHAT_HISTORY = 'UPDATE_CHAT_HISTORY';

export const CLEAR_CHAT_REQUEST = 'CLEAR_CHAT_REQUEST';
export const CLEAR_CHAT_SUCCESS = 'CLEAR_CHAT_SUCCESS';
export const CLEAR_CHAT_FAIL = 'CLEAR_CHAT_FAIL';

export const SHOW_ONLINE = 'SHOW_ONLINE';
